# Generated by Django 5.0.7 on 2026-05-26 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='service',
            name='salon',
        ),
        migrations.RemoveField(
            model_name='stylist',
            name='salon',
        ),
    ]
