# Generated by Django 5.0.7 on 2026-05-08 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salon',
            name='about_picture',
            field=models.ImageField(blank=True, null=True, upload_to='salons/about/'),
        ),
        migrations.AddField(
            model_name='salon',
            name='about_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='salon',
            name='experience',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='specialty',
            field=models.CharField(default='General', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='target_audience',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='vibe',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
