# Generated by Django 5.0.7 on 2026-05-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0002_salon_about_picture_salon_about_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='bi bi-star', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='service_subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
