# Generated by Django 5.0.7 on 2026-05-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0002_remove_portfolio_salon_remove_salon_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waitlist',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='salon',
            name='service_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='service_icon',
            field=models.CharField(default='bi bi-star', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='service_subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='service_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
