# Generated by Django 5.0.7 on 2026-05-26 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0003_remove_waitlist_service_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=100)),
                ('service_subtitle', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_icon', models.CharField(default='bi bi-star', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_icon',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_subtitle',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_title',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Salon.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='waitlist',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Salon.service'),
            preserve_default=False,
        ),
    ]
