# Generated by Django 5.0.7 on 2026-05-08 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0003_service_salon_service_subtitle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='service_subtitle',
        ),
    ]
