# Generated by Django 5.0.7 on 2026-06-03 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0004_service_remove_salon_service_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='Salon.salon'),
        ),
        migrations.AddField(
            model_name='service',
            name='salon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='Salon.salon'),
        ),
    ]
