# Generated by Django 5.0.7 on 2026-05-08 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0004_remove_salon_service_subtitle'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='salon',
            name='service_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='service_icon',
            field=models.CharField(default='bi bi-star', max_length=100),
        ),
        migrations.AddField(
            model_name='salon',
            name='service_subtitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salon',
            name='service_title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
