# Generated by Django 5.0.7 on 2026-05-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0005_delete_service_salon_service_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_subtitle', models.CharField(max_length=100)),
                ('service_title', models.CharField(max_length=100)),
                ('service_description', models.TextField()),
                ('service_icon', models.CharField(default='bi bi-star', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_description',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_icon',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_subtitle',
        ),
        migrations.RemoveField(
            model_name='salon',
            name='service_title',
        ),
    ]
