# Generated by Django 5.0.7 on 2026-05-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0007_portfolio_inspiration_inspirationmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='description',
        ),
    ]
