# Generated by Django 5.0.7 on 2026-05-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0008_remove_portfolio_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspiration',
            name='user',
        ),
    ]
