# Generated by Django 5.0.7 on 2026-05-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0009_remove_inspiration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
