# Generated by Django 5.0.7 on 2026-05-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0010_portfolio_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('style_signature', models.TextField(help_text='AI generated description for matching')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
