# Generated by Django 5.0.7 on 2026-05-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Salon', '0011_businesswork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessWork',
        ),
    ]
